development:
  adapter: postgresql
  encoding: unicode
  database: tornado_api_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: tornado_api_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: tornado_api_production
  pool: 5
